metadata.format.version = "1.1"

[versions]

minestom = "82725b5e32"
minestomext = "1.2.0"
polar = "1.6.3"
slf4j = "2.0.11"
jlineterm = "3.25.1"
jlineread = "3.25.1"

# Gradle plugins
blossom = "1.3.0"
shadowJar = "7.0.0"

[libraries]

minestom = { group = "net.minestom", name = "minestom-snapshots", version.ref = "minestom" }
minestomext = { group = "dev.hollowcube", name = "minestom-ce-extensions", version.ref = "minestomext" }
polar = { group = "dev.hollowcube", name = "polar", version.ref = "polar" }
slf4j = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }
jlineterm = { group = "org.jline", name = "jline-terminal", version.ref = "jlineterm" }
jlineread = { group = "org.jline", name = "jline-reader", version.ref = "jlineread" }

[bundles]

[plugins]

blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
shadowJar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
